// Auto marku un modeļu datubāze
// Atjaunots: 2026-04-15
// Avots: Apkopotie dati no publiskiem avotiem

export const CAR_MAKES: string[] = [
  'Abarth',
  'Alfa Romeo',
  'Alpina',
  'Alpine',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'BYD',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Cupra',
  'Dacia',
  'Daewoo',
  'Dodge',
  'DS Automobiles',
  'Ferrari',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Maserati',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'MG',
  'Mini',
  'Mitsubishi',
  'Morgan',
  'Nissan',
  'Oldsmobile',
  'Opel',
  'Peugeot',
  'Pontiac',
  'Porsche',
  'Ram',
  'Renault',
  'Rolls-Royce',
  'Rover',
  'Saab',
  'Seat',
  'Skoda',
  'Smart',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Vauxhall',
  'Volkswagen',
  'Volvo',
  'Zastava',
];

export const CAR_MODELS: Record<string, string[]> = {
  'Abarth': [
    '124 Spider',
    '500',
    '595',
    '695',
    'Punto',
  ],

  'Alfa Romeo': [
    '145',
    '146',
    '147',
    '155',
    '156',
    '159',
    '164',
    '166',
    '4C',
    'Brera',
    'Crosswagon',
    'GTV',
    'Giulia',
    'Giulietta',
    'MiTo',
    'Spider',
    'Stelvio',
    'Tonale',
  ],

  'Alpina': [
    'B3',
    'B4',
    'B5',
    'B6',
    'B7',
    'B8',
    'D3',
    'D4',
    'D5',
    'XB7',
  ],

  'Alpine': [
    'A110',
    'A290',
  ],

  'Aston Martin': [
    'DB7',
    'DB9',
    'DB11',
    'DBS',
    'DBX',
    'Rapide',
    'V8 Vantage',
    'V12 Vantage',
    'Vanquish',
    'Vantage',
  ],

  'Audi': [
    'A1',
    'A2',
    'A3',
    'A4',
    'A4 Allroad',
    'A5',
    'A6',
    'A6 Allroad',
    'A7',
    'A8',
    'e-tron',
    'e-tron GT',
    'e-tron S',
    'Q2',
    'Q3',
    'Q4 e-tron',
    'Q5',
    'Q7',
    'Q8',
    'Q8 e-tron',
    'R8',
    'RS3',
    'RS4',
    'RS5',
    'RS6',
    'RS7',
    'RS Q3',
    'RS Q8',
    'S3',
    'S4',
    'S5',
    'S6',
    'S7',
    'S8',
    'SQ5',
    'SQ7',
    'SQ8',
    'TT',
    'TTS',
    'TT RS',
  ],

  'Bentley': [
    'Arnage',
    'Bentayga',
    'Continental GT',
    'Continental Flying Spur',
    'Flying Spur',
    'Mulsanne',
  ],

  'BMW': [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'i3',
    'i4',
    'i5',
    'i7',
    'iX',
    'iX1',
    'iX3',
    'M2',
    'M3',
    'M4',
    'M5',
    'M6',
    'M8',
    'X1',
    'X2',
    'X3',
    'X3 M',
    'X4',
    'X4 M',
    'X5',
    'X5 M',
    'X6',
    'X6 M',
    'X7',
    'Z3',
    'Z4',
  ],

  'Bugatti': [
    'Chiron',
    'Divo',
    'Veyron',
  ],

  'BYD': [
    'Atto 3',
    'Han',
    'Sea Lion',
    'Seal',
    'Tang',
  ],

  'Cadillac': [
    'ATS',
    'CT4',
    'CT5',
    'CT6',
    'CTS',
    'Escalade',
    'LYRIQ',
    'SRX',
    'STS',
    'XT4',
    'XT5',
    'XT6',
  ],

  'Chevrolet': [
    'Aveo',
    'Blazer',
    'Camaro',
    'Captiva',
    'Colorado',
    'Corvette',
    'Cruze',
    'Equinox',
    'Express',
    'Impala',
    'Lacetti',
    'Malibu',
    'Matiz',
    'Niva',
    'Orlando',
    'Silverado',
    'Spark',
    'Suburban',
    'Tahoe',
    'Trailblazer',
    'Traverse',
    'Trax',
  ],

  'Chrysler': [
    '300',
    '300C',
    'Grand Voyager',
    'Pacifica',
    'PT Cruiser',
    'Sebring',
    'Town & Country',
    'Voyager',
  ],

  'Citroën': [
    'Berlingo',
    'C1',
    'C2',
    'C3',
    'C3 Aircross',
    'C3 Picasso',
    'C4',
    'C4 Cactus',
    'C4 Grand Picasso',
    'C4 Picasso',
    'C4 X',
    'C5',
    'C5 Aircross',
    'C5 X',
    'C6',
    'C8',
    'DS3',
    'DS4',
    'DS5',
    'ë-C3',
    'ë-C4',
    'Grand C4 Picasso',
    'Jumper',
    'Nemo',
    'Saxo',
    'SpaceTourer',
    'Xsara',
    'Xsara Picasso',
    'ZX',
  ],

  'Cupra': [
    'Ateca',
    'Born',
    'Formentor',
    'Leon',
    'Terramar',
  ],

  'Dacia': [
    'Bigster',
    'Dokker',
    'Duster',
    'Jogger',
    'Lodgy',
    'Logan',
    'Logan MCV',
    'Sandero',
    'Sandero Stepway',
    'Spring',
  ],

  'Daewoo': [
    'Espero',
    'Kalos',
    'Lacetti',
    'Lanos',
    'Leganza',
    'Matiz',
    'Nubira',
    'Tacuma',
  ],

  'Dodge': [
    'Avenger',
    'Caliber',
    'Challenger',
    'Charger',
    'Dakota',
    'Durango',
    'Journey',
    'Neon',
    'Nitro',
    'Ram 1500',
    'Viper',
  ],

  'DS Automobiles': [
    'DS 3',
    'DS 3 Crossback',
    'DS 4',
    'DS 5',
    'DS 7',
    'DS 7 Crossback',
    'DS 9',
  ],

  'Ferrari': [
    '296',
    '458 Italia',
    '488',
    '599',
    '612',
    'California',
    'F8 Tributo',
    'GTC4Lusso',
    'Portofino',
    'Roma',
    'SF90',
  ],

  'Fiat': [
    '124 Spider',
    '500',
    '500C',
    '500e',
    '500L',
    '500X',
    'Barchetta',
    'Bravo',
    'Croma',
    'Doblo',
    'Freemont',
    'Grande Punto',
    'Idea',
    'Linea',
    'Multipla',
    'Panda',
    'Punto',
    'Qubo',
    'Scudo',
    'Sedici',
    'Stilo',
    'Tipo',
    'Ulysse',
  ],

  'Ford': [
    'B-Max',
    'C-Max',
    'Connect',
    'Cougar',
    'EcoSport',
    'Edge',
    'Escape',
    'Explorer',
    'F-150',
    'Fiesta',
    'Focus',
    'Fusion',
    'Galaxy',
    'Grand C-Max',
    'Ka',
    'Ka+',
    'Kuga',
    'Maverick',
    'Mondeo',
    'Mustang',
    'Mustang Mach-E',
    'Puma',
    'Ranger',
    'S-Max',
    'Tourneo',
    'Transit',
    'Transit Connect',
  ],

  'Genesis': [
    'G70',
    'G80',
    'G90',
    'GV70',
    'GV80',
  ],

  'GMC': [
    'Acadia',
    'Canyon',
    'Envoy',
    'Jimmy',
    'Sierra',
    'Suburban',
    'Terrain',
    'Yukon',
  ],

  'Honda': [
    'Accord',
    'City',
    'Civic',
    'Civic e:HEV',
    'CR-V',
    'CR-Z',
    'e',
    'e:Ny1',
    'FR-V',
    'HR-V',
    'Insight',
    'Jazz',
    'Legend',
    'Logo',
    'Odyssey',
    'Pilot',
    'Prelude',
    'Ridgeline',
    'Stream',
    'ZR-V',
  ],

  'Hummer': [
    'H1',
    'H2',
    'H3',
  ],

  'Hyundai': [
    'Accent',
    'Bayon',
    'Coupe',
    'Elantra',
    'Getz',
    'Grand Santa Fe',
    'i10',
    'i20',
    'i30',
    'i30 N',
    'i40',
    'IONIQ',
    'IONIQ 5',
    'IONIQ 6',
    'ix20',
    'ix35',
    'ix55',
    'Kona',
    'Kona Electric',
    'Matrix',
    'Nexo',
    'Santa Fe',
    'Sonata',
    'Staria',
    'Terracan',
    'Tucson',
    'Veloster',
  ],

  'Infiniti': [
    'EX',
    'FX',
    'G',
    'M',
    'Q30',
    'Q50',
    'Q60',
    'Q70',
    'QX30',
    'QX50',
    'QX60',
    'QX70',
    'QX80',
  ],

  'Isuzu': [
    'D-Max',
    'MU-X',
    'Trooper',
  ],

  'Jaguar': [
    'E-Pace',
    'F-Pace',
    'F-Type',
    'I-Pace',
    'S-Type',
    'X-Type',
    'XE',
    'XF',
    'XJ',
    'XK',
  ],

  'Jeep': [
    'Cherokee',
    'Commander',
    'Compass',
    'Grand Cherokee',
    'Gladiator',
    'Patriot',
    'Renegade',
    'Wrangler',
  ],

  'Kia': [
    'Carens',
    'Carnival',
    'Ceed',
    'Ceed SW',
    'EV6',
    'EV9',
    'Joice',
    'Niro',
    'Optima',
    'Picanto',
    'Pro Ceed',
    'ProCeed',
    'Rio',
    'Sorento',
    'Soul',
    'Sportage',
    'Stinger',
    'Stonic',
    'Venga',
    'XCeed',
  ],

  'Lamborghini': [
    'Aventador',
    'Gallardo',
    'Huracán',
    'Urus',
  ],

  'Lancia': [
    'Delta',
    'Lybra',
    'Musa',
    'Phedra',
    'Thesis',
    'Ypsilon',
  ],

  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'Freelander',
    'Range Rover',
    'Range Rover Evoque',
    'Range Rover Sport',
    'Range Rover Velar',
  ],

  'Lexus': [
    'CT',
    'ES',
    'GS',
    'GX',
    'IS',
    'LC',
    'LM',
    'LS',
    'LX',
    'NX',
    'RC',
    'RX',
    'UX',
  ],

  'Lincoln': [
    'Aviator',
    'Continental',
    'Corsair',
    'MKC',
    'MKS',
    'MKT',
    'MKX',
    'MKZ',
    'Navigator',
  ],

  'Lotus': [
    'Elise',
    'Emira',
    'Evija',
    'Evora',
    'Exige',
  ],

  'Maserati': [
    'Ghibli',
    'GranCabrio',
    'GranTurismo',
    'Grecale',
    'Levante',
    'MC20',
    'Quattroporte',
  ],

  'Maybach': [
    '57',
    '62',
    'GLS',
    'S-Class',
  ],

  'Mazda': [
    '2',
    '3',
    '5',
    '6',
    'CX-3',
    'CX-30',
    'CX-5',
    'CX-60',
    'CX-7',
    'CX-9',
    'MX-5',
    'MX-30',
    'MX-30 R-EV',
    'RX-8',
  ],

  'McLaren': [
    '570S',
    '600LT',
    '650S',
    '720S',
    'Artura',
    'GT',
  ],

  'Mercedes-Benz': [
    'A-Class',
    'AMG GT',
    'B-Class',
    'C-Class',
    'CLA',
    'CLA Shooting Brake',
    'CLE',
    'CLS',
    'E-Class',
    'EQA',
    'EQB',
    'EQC',
    'EQE',
    'EQE SUV',
    'EQS',
    'EQS SUV',
    'G-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLC Coupe',
    'GLE',
    'GLE Coupe',
    'GLS',
    'Marco Polo',
    'S-Class',
    'SL',
    'SLC',
    'Sprinter',
    'V-Class',
    'Viano',
    'Vito',
  ],

  'MG': [
    '3',
    '4',
    '5',
    'Cyberster',
    'EHS',
    'Marvel R',
    'HS',
    'ZS',
    'ZS EV',
  ],

  'Mini': [
    'Cabrio',
    'Clubman',
    'Cooper',
    'Cooper S',
    'Countryman',
    'Coupe',
    'John Cooper Works',
    'One',
    'Paceman',
    'Roadster',
  ],

  'Mitsubishi': [
    'ASX',
    'Carisma',
    'Colt',
    'Eclipse Cross',
    'Galant',
    'Grandis',
    'L200',
    'Lancer',
    'Outlander',
    'Outlander PHEV',
    'Pajero',
    'Space Star',
  ],

  'Morgan': [
    '3 Wheeler',
    'Plus 4',
    'Plus 6',
    'Roadster',
  ],

  'Nissan': [
    '350Z',
    '370Z',
    'Almera',
    'Ariya',
    'GT-R',
    'Juke',
    'Leaf',
    'Maxima',
    'Micra',
    'Murano',
    'Navara',
    'Note',
    'Pathfinder',
    'Patrol',
    'Pixo',
    'Primera',
    'Pulsar',
    'Qashqai',
    'Sunny',
    'Terrano',
    'Tiida',
    'X-Trail',
    'Z',
  ],

  'Opel': [
    'Adam',
    'Agila',
    'Ampera',
    'Ampera-e',
    'Antara',
    'Astra',
    'Astra Sports Tourer',
    'Cascada',
    'Combo',
    'Corsa',
    'Corsa-e',
    'Crossland',
    'Frontera',
    'Grandland',
    'Grandland X',
    'Insignia',
    'Meriva',
    'Mokka',
    'Mokka-e',
    'Movano',
    'Omega',
    'Signum',
    'Sintra',
    'Tigra',
    'Vectra',
    'Vivaro',
    'Zafira',
    'Zafira Tourer',
  ],

  'Peugeot': [
    '1007',
    '106',
    '107',
    '108',
    '2008',
    '206',
    '207',
    '208',
    '3008',
    '301',
    '306',
    '307',
    '308',
    '4007',
    '4008',
    '406',
    '407',
    '408',
    '5008',
    '508',
    '607',
    '807',
    'e-208',
    'e-2008',
    'Expert',
    'Ion',
    'Partner',
    'RCZ',
    'Traveller',
  ],

  'Pontiac': [
    'Aztek',
    'Bonneville',
    'Firebird',
    'G6',
    'GTO',
    'Solstice',
    'Sunfire',
    'Trans Am',
  ],

  'Porsche': [
    '718 Boxster',
    '718 Cayman',
    '911',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
  ],

  'Ram': [
    '1500',
    '2500',
    '3500',
    'ProMaster',
  ],

  'Renault': [
    'Arkana',
    'Austral',
    'Captur',
    'Clio',
    'Espace',
    'Fluence',
    'Grand Scenic',
    'Kadjar',
    'Kangoo',
    'Koleos',
    'Laguna',
    'Latitude',
    'Logan',
    'Master',
    'Megane',
    'Megane E-Tech',
    'Modus',
    'Rafale',
    'Sandero',
    'Scenic',
    'Scenic E-Tech',
    'Symbol',
    'Trafic',
    'Twingo',
    'Vel Satis',
    'Zoe',
  ],

  'Rolls-Royce': [
    'Cullinan',
    'Dawn',
    'Ghost',
    'Phantom',
    'Silver Shadow',
    'Silver Spur',
    'Spectre',
    'Wraith',
  ],

  'Rover': [
    '25',
    '45',
    '75',
    'City Rover',
    'Streetwise',
  ],

  'Saab': [
    '9-3',
    '9-5',
    '9-7X',
  ],

  'Seat': [
    'Alhambra',
    'Altea',
    'Arona',
    'Ateca',
    'Cordoba',
    'Exeo',
    'Ibiza',
    'Leon',
    'Mii',
    'Tarraco',
    'Toledo',
  ],

  'Skoda': [
    'Citigo',
    'Enyaq',
    'Enyaq Coupe',
    'Fabia',
    'Kamiq',
    'Karoq',
    'Kodiaq',
    'Kodiaq RS',
    'Octavia',
    'Octavia RS',
    'Rapid',
    'Roomster',
    'Scala',
    'Slavia',
    'Superb',
    'Yeti',
  ],

  'Smart': [
    '#1',
    '#3',
    'Forfour',
    'Fortwo',
    'Roadster',
  ],

  'SsangYong': [
    'Actyon',
    'Korando',
    'Musso',
    'Rexton',
    'Rodius',
    'Tivoli',
    'Torres',
    'XLV',
  ],

  'Subaru': [
    'BRZ',
    'Forester',
    'Impreza',
    'Legacy',
    'Levorg',
    'Outback',
    'Solterra',
    'WRX',
    'XV',
  ],

  'Suzuki': [
    'Alto',
    'Baleno',
    'Celerio',
    'Grand Vitara',
    'Ignis',
    'Jimny',
    'Kizashi',
    'Liana',
    'S-Cross',
    'Splash',
    'Swift',
    'SX4',
    'SX4 S-Cross',
    'Vitara',
    'Wagon R+',
  ],

  'Tesla': [
    'Cybertruck',
    'Model 3',
    'Model S',
    'Model X',
    'Model Y',
    'Roadster',
  ],

  'Toyota': [
    'Avensis',
    'Aygo',
    'Aygo X',
    'bZ4X',
    'C-HR',
    'Camry',
    'Corolla',
    'Corolla Cross',
    'Crown',
    'FJ Cruiser',
    'GR86',
    'GR Corolla',
    'GR Supra',
    'GR Yaris',
    'Highlander',
    'Hilux',
    'Land Cruiser',
    'Land Cruiser 300',
    'Previa',
    'Prius',
    'Proace',
    'RAV4',
    'RAV4 Plug-in',
    'Sequoia',
    'Tacoma',
    'Tundra',
    'Urban Cruiser',
    'Verso',
    'Yaris',
    'Yaris Cross',
  ],

  'Vauxhall': [
    'Astra',
    'Corsa',
    'Crossland',
    'Grandland',
    'Insignia',
    'Mokka',
    'Vivaro',
    'Zafira',
  ],

  'Volkswagen': [
    'Amarok',
    'Arteon',
    'Beetle',
    'Bora',
    'Caddy',
    'California',
    'Caravelle',
    'CC',
    'Crafter',
    'Fox',
    'Golf',
    'Golf Plus',
    'Golf Sportsvan',
    'ID.2',
    'ID.3',
    'ID.4',
    'ID.5',
    'ID.7',
    'Jetta',
    'Lupo',
    'Multivan',
    'Passat',
    'Passat Alltrack',
    'Phaeton',
    'Polo',
    'Scirocco',
    'Sharan',
    'T-Cross',
    'T-Roc',
    'Taigo',
    'Tiguan',
    'Tiguan Allspace',
    'Touareg',
    'Touran',
    'Transporter',
    'up!',
  ],

  'Volvo': [
    'C30',
    'C40',
    'C70',
    'EC40',
    'EM90',
    'EX30',
    'EX40',
    'EX90',
    'S40',
    'S60',
    'S70',
    'S80',
    'S90',
    'V40',
    'V40 Cross Country',
    'V50',
    'V60',
    'V60 Cross Country',
    'V70',
    'V90',
    'V90 Cross Country',
    'XC40',
    'XC60',
    'XC70',
    'XC90',
  ],

  'Zastava': [
    '101',
    '128',
    'Florida',
    'Yugo',
  ],
};

export const TOP_CAR_MAKES: string[] = [
  'Mercedes-Benz', 'BMW', 'Audi', 'Volkswagen', 'Porsche',
  'Ford', 'Skoda', 'Opel', 'Toyota', 'Volvo',
];

export interface CarModelGroup {
  group: string;
  models: string[];
}

export const CAR_MODELS_GROUPED: Record<string, CarModelGroup[]> = {
  'BMW': [
    { group: '1 Series', models: ['1 Series (All)', '114', '116', '116d', '118', '118d', '120', '120d', '123', '125', '125d', '128', '130', '135', '135i', '1er M Coupé'] },
    { group: '2 Series', models: ['2 Series (All)', '214 Active Tourer', '214 Gran Tourer', '216', '216 Active Tourer', '216 Gran Tourer', '218', '218 Active Tourer', '220', '220 Active Tourer', '225', '228', '230', 'M2', 'M235'] },
    { group: '3 Series', models: ['3 Series (All)', '316', '316d', '318', '318d', '318i', '320', '320d', '320i', '323', '325', '325d', '325i', '328', '328i', '330', '330d', '330i', '335', '335d', '335i', '340', 'M3'] },
    { group: '4 Series', models: ['4 Series (All)', '418', '418d', '420', '420d', '420i', '425', '428', '428i', '430', '430d', '430i', '435', '440', 'M4'] },
    { group: '5 Series', models: ['5 Series (All)', '516', '518', '518d', '520', '520d', '520i', '523', '525', '525d', '525i', '528', '528i', '530', '530d', '530i', '535', '535d', '535i', '540', '540d', '540i', 'M5'] },
    { group: '6 Series', models: ['6 Series (All)', '620', '625', '628', '630', '635', '640', '645', '650', 'M6'] },
    { group: '7 Series', models: ['7 Series (All)', '730', '730d', '730i', '735', '735d', '735i', '740', '740d', '740i', '745', '745d', '750', '750i', '760', 'M760'] },
    { group: '8 Series', models: ['8 Series (All)', '840', '840i', '850', 'M8'] },
    { group: 'X1', models: ['X1 (All)', 'sDrive16d', 'sDrive18d', 'sDrive18i', 'sDrive20d', 'sDrive20i', 'xDrive18d', 'xDrive20d', 'xDrive20i', 'xDrive25d', 'xDrive28i'] },
    { group: 'X2', models: ['X2 (All)', 'sDrive18d', 'sDrive18i', 'sDrive20i', 'xDrive18d', 'xDrive20d', 'xDrive20i', 'xDrive25e', 'M35i'] },
    { group: 'X3', models: ['X3 (All)', 'sDrive18d', 'sDrive18i', 'xDrive20d', 'xDrive20i', 'xDrive25d', 'xDrive25i', 'xDrive30d', 'xDrive30i', 'xDrive35d', 'xDrive35i', 'M40d', 'M40i', 'M'] },
    { group: 'X4', models: ['X4 (All)', 'xDrive20d', 'xDrive20i', 'xDrive25d', 'xDrive28i', 'xDrive30d', 'xDrive30i', 'xDrive35d', 'M40d', 'M40i', 'M'] },
    { group: 'X5', models: ['X5 (All)', 'sDrive25d', 'xDrive25d', 'xDrive30d', 'xDrive30i', 'xDrive35d', 'xDrive35i', 'xDrive40d', 'xDrive40i', 'xDrive45e', 'xDrive50i', 'M50d', 'M50i', 'M'] },
    { group: 'X6', models: ['X6 (All)', 'xDrive30d', 'xDrive30i', 'xDrive35d', 'xDrive35i', 'xDrive40d', 'xDrive40i', 'xDrive50i', 'M50d', 'M50i', 'M'] },
    { group: 'X7', models: ['X7 (All)', 'xDrive30d', 'xDrive30i', 'xDrive40d', 'xDrive40i', 'M50d', 'M50i', 'M60i'] },
    { group: 'Z Series', models: ['Z3', 'Z4', 'Z8'] },
    { group: 'i Series', models: ['i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX1', 'iX2', 'iX3'] },
  ],
  'Mercedes-Benz': [
    { group: 'A-Class', models: ['A-Class (All)', 'A 140', 'A 150', 'A 160', 'A 170', 'A 180', 'A 200', 'A 210', 'A 220', 'A 250', 'A 35 AMG', 'A 45 AMG'] },
    { group: 'B-Class', models: ['B-Class (All)', 'B 150', 'B 160', 'B 170', 'B 180', 'B 200', 'B 220', 'B 250'] },
    { group: 'C-Class', models: ['C-Class (All)', 'C 160', 'C 180', 'C 200', 'C 220', 'C 230', 'C 240', 'C 250', 'C 270', 'C 280', 'C 300', 'C 320', 'C 350', 'C 400', 'C 43 AMG', 'C 63 AMG'] },
    { group: 'CLA', models: ['CLA (All)', 'CLA 180', 'CLA 200', 'CLA 220', 'CLA 250', 'CLA 35 AMG', 'CLA 45 AMG'] },
    { group: 'CLS', models: ['CLS (All)', 'CLS 220', 'CLS 250', 'CLS 300', 'CLS 320', 'CLS 350', 'CLS 400', 'CLS 450', 'CLS 500', 'CLS 53 AMG', 'CLS 63 AMG'] },
    { group: 'E-Class', models: ['E-Class (All)', 'E 160', 'E 180', 'E 200', 'E 220', 'E 230', 'E 240', 'E 250', 'E 270', 'E 280', 'E 300', 'E 320', 'E 350', 'E 400', 'E 450', 'E 500', 'E 53 AMG', 'E 63 AMG'] },
    { group: 'G-Class', models: ['G-Class (All)', 'G 300', 'G 320', 'G 350', 'G 400', 'G 500', 'G 55 AMG', 'G 63 AMG', 'G 65 AMG'] },
    { group: 'GLA', models: ['GLA (All)', 'GLA 180', 'GLA 200', 'GLA 220', 'GLA 250', 'GLA 35 AMG', 'GLA 45 AMG'] },
    { group: 'GLB', models: ['GLB (All)', 'GLB 180', 'GLB 200', 'GLB 220', 'GLB 250', 'GLB 35 AMG'] },
    { group: 'GLC', models: ['GLC (All)', 'GLC 200', 'GLC 220', 'GLC 250', 'GLC 300', 'GLC 350', 'GLC 400', 'GLC 43 AMG', 'GLC 63 AMG'] },
    { group: 'GLE', models: ['GLE (All)', 'GLE 250', 'GLE 300', 'GLE 350', 'GLE 400', 'GLE 450', 'GLE 500', 'GLE 53 AMG', 'GLE 63 AMG'] },
    { group: 'GLS', models: ['GLS (All)', 'GLS 350', 'GLS 400', 'GLS 450', 'GLS 500', 'GLS 580', 'GLS 63 AMG'] },
    { group: 'S-Class', models: ['S-Class (All)', 'S 280', 'S 300', 'S 320', 'S 350', 'S 400', 'S 420', 'S 430', 'S 450', 'S 500', 'S 550', 'S 560', 'S 580', 'S 600', 'S 63 AMG', 'S 65 AMG'] },
    { group: 'SL', models: ['SL (All)', 'SL 280', 'SL 300', 'SL 320', 'SL 350', 'SL 400', 'SL 420', 'SL 450', 'SL 500', 'SL 550', 'SL 55 AMG', 'SL 600', 'SL 63 AMG', 'SL 65 AMG'] },
    { group: 'V-Class / Vito', models: ['Vito', 'Viano', 'V 200', 'V 220', 'V 230', 'V 250', 'V 280', 'V 300'] },
    { group: 'EQ', models: ['EQA', 'EQB', 'EQC', 'EQE', 'EQE SUV', 'EQS', 'EQS SUV', 'EQV'] },
    { group: 'Sprinter', models: ['Sprinter (All)', '208 CDI', '211 CDI', '213 CDI', '216 CDI', '219 CDI', '311 CDI', '313 CDI', '316 CDI', '319 CDI'] },
  ],
  'Audi': [
    { group: 'A1', models: ['A1 (All)', '1.0 TFSI', '1.2 TFSI', '1.4 TFSI', '1.6 TDI', '1.8 TFSI', '2.0 TFSI', 'S1'] },
    { group: 'A3', models: ['A3 (All)', '1.2 TFSI', '1.4 TFSI', '1.6', '1.6 TDI', '1.8 TFSI', '2.0 TDI', '2.0 TFSI', 'S3', 'RS3'] },
    { group: 'A4', models: ['A4 (All)', '1.6', '1.8 T', '1.8 TFSI', '2.0 TDI', '2.0 TFSI', '2.4', '2.5 TDI', '2.7 TDI', '2.8', '3.0 TDI', '3.0 TFSI', '3.2 FSI', 'S4', 'RS4'] },
    { group: 'A5', models: ['A5 (All)', '1.8 TFSI', '2.0 TDI', '2.0 TFSI', '2.7 TDI', '3.0 TDI', '3.0 TFSI', 'S5', 'RS5'] },
    { group: 'A6', models: ['A6 (All)', '1.8 T', '2.0 TDI', '2.0 TFSI', '2.4', '2.5 TDI', '2.7 TDI', '2.8', '2.8 FSI', '3.0 TDI', '3.0 TFSI', '3.2 FSI', '4.2', 'S6', 'RS6'] },
    { group: 'A7', models: ['A7 (All)', '2.0 TDI', '2.8 FSI', '3.0 TDI', '3.0 TFSI', 'S7', 'RS7'] },
    { group: 'A8', models: ['A8 (All)', '2.8', '3.0 TDI', '3.0 TFSI', '3.7', '4.0 TFSI', '4.2', '4.2 TDI', '6.0', 'S8'] },
    { group: 'Q2', models: ['Q2 (All)', '1.0 TFSI', '1.4 TFSI', '1.6 TDI', '2.0 TDI', '2.0 TFSI', 'SQ2'] },
    { group: 'Q3', models: ['Q3 (All)', '1.4 TFSI', '2.0 TDI', '2.0 TFSI', 'RS Q3'] },
    { group: 'Q4 e-tron', models: ['Q4 e-tron (All)', 'Q4 35 e-tron', 'Q4 40 e-tron', 'Q4 45 e-tron', 'Q4 50 e-tron quattro'] },
    { group: 'Q5', models: ['Q5 (All)', '2.0 TDI', '2.0 TFSI', '3.0 TDI', '3.0 TFSI', 'SQ5'] },
    { group: 'Q7', models: ['Q7 (All)', '3.0 TDI', '3.0 TFSI', '4.2 TDI', '4.2 FSI', 'SQ7'] },
    { group: 'Q8', models: ['Q8 (All)', '55 TFSI', 'SQ8', 'RS Q8', 'Q8 e-tron', 'Q8 Sportback e-tron'] },
    { group: 'TT', models: ['TT (All)', 'TT Coupé', 'TT Roadster', '1.8 T', '2.0 TFSI', '3.2', 'TTS', 'TTRS'] },
    { group: 'R8', models: ['R8 (All)', '4.2 FSI', '5.2 FSI', 'V10', 'GT', 'LMS'] },
    { group: 'e-tron', models: ['e-tron', 'e-tron S', 'e-tron Sportback', 'e-tron GT', 'RS e-tron GT'] },
  ],
  'Volkswagen': [
    { group: 'Golf', models: ['Golf (All)', 'Golf I', 'Golf II', 'Golf III', 'Golf IV', 'Golf V', 'Golf VI', 'Golf VII', 'Golf VIII', 'GTI', 'GTD', 'GTE', 'R', 'e-Golf'] },
    { group: 'Polo', models: ['Polo (All)', 'Polo I', 'Polo II', 'Polo III', 'Polo IV', 'Polo V', 'Polo VI', 'GTI', 'R WRC'] },
    { group: 'Passat', models: ['Passat (All)', 'Passat B3', 'Passat B4', 'Passat B5', 'Passat B6', 'Passat B7', 'Passat B8', 'GTE', 'R-Line', 'Alltrack'] },
    { group: 'Tiguan', models: ['Tiguan (All)', '1.4 TSI', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'Allspace', 'R-Line', 'R'] },
    { group: 'Touareg', models: ['Touareg (All)', 'Touareg I', 'Touareg II', 'Touareg III', 'R-Line', 'R50', 'Hybrid'] },
    { group: 'T-Roc', models: ['T-Roc (All)', '1.0 TSI', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'Cabrio', 'R'] },
    { group: 'T-Cross', models: ['T-Cross (All)', '1.0 TSI', '1.5 TSI', '1.6 TDI'] },
    { group: 'Touran', models: ['Touran (All)', '1.2 TSI', '1.4 TSI', '1.6 TDI', '2.0 TDI'] },
    { group: 'Sharan', models: ['Sharan (All)', '1.4 TSI', '1.8 T', '2.0 TDI', '2.0 TSI', '2.8 VR6'] },
    { group: 'ID.', models: ['ID.3', 'ID.4', 'ID.5', 'ID.6', 'ID.7', 'ID. Buzz'] },
    { group: 'Arteon', models: ['Arteon (All)', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'Shooting Brake', 'R'] },
    { group: 'Caddy', models: ['Caddy (All)', 'Caddy II', 'Caddy III', 'Caddy IV', '1.6 TDI', '2.0 TDI'] },
    { group: 'Transporter', models: ['Transporter (All)', 'T3', 'T4', 'T5', 'T6', 'T7', 'Caravelle', 'Multivan'] },
  ],
  'Porsche': [
    { group: '911', models: ['911 (All)', 'Carrera', 'Carrera 4', 'Carrera S', 'Carrera 4S', 'Targa', 'Targa 4', 'Turbo', 'Turbo S', 'GT3', 'GT3 RS', 'GT2', 'GT2 RS'] },
    { group: 'Cayenne', models: ['Cayenne (All)', 'Cayenne', 'Cayenne S', 'Cayenne GTS', 'Cayenne Turbo', 'Cayenne Turbo S', 'Cayenne E-Hybrid', 'Coupe'] },
    { group: 'Macan', models: ['Macan (All)', 'Macan', 'Macan S', 'Macan GTS', 'Macan Turbo', 'Macan Electric'] },
    { group: 'Panamera', models: ['Panamera (All)', 'Panamera', 'Panamera 4', 'Panamera S', 'Panamera GTS', 'Panamera Turbo', '4 E-Hybrid', 'Sport Turismo'] },
    { group: 'Taycan', models: ['Taycan (All)', 'Taycan', 'Taycan 4S', 'Taycan GTS', 'Taycan Turbo', 'Taycan Turbo S', 'Cross Turismo', 'Sport Turismo'] },
    { group: 'Boxster', models: ['Boxster (All)', '718 Boxster', '718 Boxster S', '718 Boxster GTS', '718 Spyder'] },
    { group: 'Cayman', models: ['Cayman (All)', '718 Cayman', '718 Cayman S', '718 Cayman GTS', '718 Cayman GT4'] },
  ],
  'Ford': [
    { group: 'Fiesta', models: ['Fiesta (All)', 'Fiesta IV', 'Fiesta V', 'Fiesta VI', 'Fiesta VII', 'ST', 'Active'] },
    { group: 'Focus', models: ['Focus (All)', 'Focus I', 'Focus II', 'Focus III', 'Focus IV', 'ST', 'RS', 'Active'] },
    { group: 'Mondeo', models: ['Mondeo (All)', 'Mondeo I', 'Mondeo II', 'Mondeo III', 'Mondeo IV', 'Mondeo V', 'ST200'] },
    { group: 'Kuga', models: ['Kuga (All)', 'Kuga I', 'Kuga II', 'Kuga III', '1.5 EcoBoost', '2.0 EcoBlue', '2.5 PHEV', 'ST-Line'] },
    { group: 'Puma', models: ['Puma (All)', '1.0 EcoBoost', '1.5 EcoBoost', 'ST', 'ST-Line'] },
    { group: 'Mustang', models: ['Mustang (All)', '2.3 EcoBoost', '5.0 V8', 'GT', 'Shelby GT350', 'Shelby GT500', 'Mach-E'] },
    { group: 'Ranger', models: ['Ranger (All)', '2.0 EcoBlue', '2.2 TDCI', '3.2 TDCI', 'Raptor', 'Wildtrak'] },
    { group: 'Explorer', models: ['Explorer (All)', '2.3 EcoBoost', '3.0 V6', 'PHEV', 'ST'] },
    { group: 'Galaxy', models: ['Galaxy (All)', 'Galaxy I', 'Galaxy II', 'Galaxy III'] },
    { group: 'S-Max', models: ['S-Max (All)', '2.0 EcoBlue', '2.0 EcoBoost', '2.5 PHEV', 'ST-Line'] },
    { group: 'EcoSport', models: ['EcoSport (All)', '1.0 EcoBoost', '1.5 TDCi', '2.0 Duratec'] },
  ],
  'Skoda': [
    { group: 'Octavia', models: ['Octavia (All)', 'Octavia I', 'Octavia II', 'Octavia III', 'Octavia IV', 'RS', 'Scout', 'Combi'] },
    { group: 'Fabia', models: ['Fabia (All)', 'Fabia I', 'Fabia II', 'Fabia III', 'Fabia IV', 'RS', 'Monte Carlo', 'Combi'] },
    { group: 'Superb', models: ['Superb (All)', 'Superb I', 'Superb II', 'Superb III', 'L&K', 'Sportline', 'iV PHEV', 'Combi'] },
    { group: 'Kodiaq', models: ['Kodiaq (All)', '1.4 TSI', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'RS', 'Scout', 'Sportline'] },
    { group: 'Karoq', models: ['Karoq (All)', '1.0 TSI', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'Scout', 'Sportline'] },
    { group: 'Kamiq', models: ['Kamiq (All)', '1.0 TSI', '1.5 TSI', '1.6 TDI', 'Monte Carlo'] },
    { group: 'Scala', models: ['Scala (All)', '1.0 TSI', '1.5 TSI', '1.6 TDI', 'Monte Carlo'] },
    { group: 'Enyaq', models: ['Enyaq iV (All)', 'Enyaq 50', 'Enyaq 60', 'Enyaq 80', 'Enyaq 80x', 'Enyaq RS', 'Enyaq Coupé'] },
    { group: 'Rapid', models: ['Rapid (All)', '1.2 TSI', '1.6 MPI', '1.6 TDI', 'Spaceback'] },
  ],
  'Opel': [
    { group: 'Astra', models: ['Astra (All)', 'Astra F', 'Astra G', 'Astra H', 'Astra J', 'Astra K', 'Astra L', 'GTC', 'OPC', 'Sports Tourer', 'Electric'] },
    { group: 'Corsa', models: ['Corsa (All)', 'Corsa A', 'Corsa B', 'Corsa C', 'Corsa D', 'Corsa E', 'Corsa F', 'OPC', 'Electric'] },
    { group: 'Insignia', models: ['Insignia (All)', 'Insignia A', 'Insignia B', 'OPC', 'Sports Tourer', 'Grand Sport'] },
    { group: 'Mokka', models: ['Mokka (All)', 'Mokka', 'Mokka X', 'Mokka B', 'Electric'] },
    { group: 'Crossland', models: ['Crossland (All)', 'Crossland X', '1.2 Turbo', '1.5 CDTI'] },
    { group: 'Grandland', models: ['Grandland (All)', 'Grandland X', '1.2 Turbo', '1.5 CDTI', '1.6 Turbo PHEV', 'Ultimate'] },
    { group: 'Zafira', models: ['Zafira (All)', 'Zafira A', 'Zafira B', 'Zafira C', 'Tourer', 'Life'] },
    { group: 'Vectra', models: ['Vectra (All)', 'Vectra A', 'Vectra B', 'Vectra C', 'OPC', 'Caravan'] },
    { group: 'Meriva', models: ['Meriva (All)', 'Meriva A', 'Meriva B'] },
    { group: 'Combo', models: ['Combo (All)', 'Combo C', 'Combo D', 'Combo E', 'Life', 'Cargo'] },
  ],
  'Toyota': [
    { group: 'Yaris', models: ['Yaris (All)', 'Yaris I', 'Yaris II', 'Yaris III', 'Yaris IV', 'Cross', 'GR Yaris', 'Hybrid'] },
    { group: 'Corolla', models: ['Corolla (All)', 'E10', 'E11', 'E12', 'E15', 'E16', 'E21', '1.8 Hybrid', '2.0 Hybrid', 'GR Corolla', 'Cross Hybrid'] },
    { group: 'Camry', models: ['Camry (All)', '2.0', '2.2', '2.4', '2.5 Hybrid', '3.0', '3.5'] },
    { group: 'RAV4', models: ['RAV4 (All)', 'RAV4 I', 'RAV4 II', 'RAV4 III', 'RAV4 IV', 'RAV4 V', '2.5 Hybrid', 'PHEV'] },
    { group: 'C-HR', models: ['C-HR (All)', '1.2 Turbo', '1.8 Hybrid', '2.0 Hybrid'] },
    { group: 'Land Cruiser', models: ['Land Cruiser (All)', '70', '80', '90', '100', '200', '300', 'Prado', 'Amazon'] },
    { group: 'Hilux', models: ['Hilux (All)', '2.4 D-4D', '2.5 D-4D', '2.7', '3.0 D-4D', '4.0 V6'] },
    { group: 'Prius', models: ['Prius (All)', 'Prius I', 'Prius II', 'Prius III', 'Prius IV', 'Prius V', 'Plus', 'PHV'] },
    { group: 'GR Supra', models: ['Supra (All)', 'A60', 'A70', 'A80', 'A90 GR'] },
    { group: 'bZ4X', models: ['bZ4X (All)', 'bZ4X AWD', 'bZ4X FWD'] },
  ],
  'Volvo': [
    { group: 'S60', models: ['S60 (All)', 'S60 I', 'S60 II', 'S60 III', 'D3', 'D4', 'D5', 'T4', 'T5', 'T6', 'T8', 'R-Design', 'Polestar', 'Recharge'] },
    { group: 'S90', models: ['S90 (All)', 'D3', 'D4', 'D5', 'T5', 'T6', 'T8', 'R-Design', 'Inscription', 'Recharge'] },
    { group: 'V40', models: ['V40 (All)', 'D2', 'T2', 'T3', 'T4', 'T5', 'Cross Country', 'R-Design', 'Polestar'] },
    { group: 'V60', models: ['V60 (All)', 'V60 I', 'V60 II', 'D3', 'D4', 'D5', 'T4', 'T5', 'T6', 'T8', 'R-Design', 'Polestar', 'Recharge', 'Cross Country'] },
    { group: 'V90', models: ['V90 (All)', 'D4', 'D5', 'T5', 'T6', 'T8', 'R-Design', 'Inscription', 'Recharge', 'Cross Country'] },
    { group: 'XC40', models: ['XC40 (All)', '1.5 T2', '1.5 T3', '2.0 B4', '2.0 B5', 'D3', 'D4', 'T3', 'T4', 'T5', 'R-Design', 'Recharge', 'Pure Electric'] },
    { group: 'XC60', models: ['XC60 (All)', 'XC60 I', 'XC60 II', 'D3', 'D4', 'D5', 'T5', 'T6', 'T8', 'R-Design', 'Inscription', 'Polestar', 'Recharge'] },
    { group: 'XC90', models: ['XC90 (All)', 'XC90 I', 'XC90 II', 'D3', 'D4', 'D5', 'T5', 'T6', 'T8', 'R-Design', 'Inscription', 'Polestar', 'Recharge'] },
    { group: 'C30', models: ['C30 (All)', '1.6', '1.6D', '2.0', '2.0D', 'T5', 'R-Design'] },
  ],
  'Renault': [
    { group: 'Clio', models: ['Clio (All)', 'Clio I', 'Clio II', 'Clio III', 'Clio IV', 'Clio V', 'RS', 'E-Tech'] },
    { group: 'Mégane', models: ['Mégane (All)', 'Mégane I', 'Mégane II', 'Mégane III', 'Mégane IV', 'RS', 'GT', 'E-Tech', 'E-TECH Electric'] },
    { group: 'Captur', models: ['Captur (All)', 'Captur I', 'Captur II', '1.0 TCe', '1.3 TCe', 'E-Tech PHEV'] },
    { group: 'Kadjar', models: ['Kadjar (All)', '1.2 TCe', '1.3 TCe', '1.5 dCi', '1.6 dCi'] },
    { group: 'Koleos', models: ['Koleos (All)', 'Koleos I', 'Koleos II', '1.6 dCi', '2.0 dCi', '2.5'] },
    { group: 'Laguna', models: ['Laguna (All)', 'Laguna I', 'Laguna II', 'Laguna III', 'GT', 'Coupé'] },
    { group: 'Scenic', models: ['Scenic (All)', 'Scenic I', 'Scenic II', 'Scenic III', 'Scenic IV', 'Grand Scenic', 'E-Tech Electric'] },
    { group: 'Zoe', models: ['Zoe (All)', 'Zoe I', 'Zoe II', 'R90', 'R110', 'R135'] },
    { group: 'Austral', models: ['Austral (All)', '1.2 TCe', 'E-Tech Hybrid', 'E-Tech PHEV'] },
  ],
  'Peugeot': [
    { group: '208', models: ['208 (All)', '208 I', '208 II', '1.0 PureTech', '1.2 PureTech', '1.6 THP', '1.6 BlueHDi', 'GTi', 'e-208'] },
    { group: '308', models: ['308 (All)', '308 I', '308 II', '308 III', '1.2 PureTech', '1.5 BlueHDi', '2.0 BlueHDi', 'GT', 'GTi', 'e-308', 'PHEV'] },
    { group: '2008', models: ['2008 (All)', '2008 I', '2008 II', '1.2 PureTech', '1.5 BlueHDi', 'GT', 'e-2008'] },
    { group: '3008', models: ['3008 (All)', '3008 I', '3008 II', '1.2 PureTech', '1.5 BlueHDi', '2.0 BlueHDi', 'GT', 'PHEV'] },
    { group: '5008', models: ['5008 (All)', '5008 I', '5008 II', '1.2 PureTech', '1.5 BlueHDi', '2.0 BlueHDi', 'GT'] },
    { group: '508', models: ['508 (All)', '508 I', '508 II', '1.5 BlueHDi', '2.0 BlueHDi', 'GT', 'SW', 'PHEV', 'PSE'] },
    { group: 'Partner', models: ['Partner (All)', 'Partner I', 'Partner II', 'Partner III'] },
    { group: 'Expert', models: ['Expert (All)', 'Expert I', 'Expert II', 'Expert III'] },
  ],
  'Citroën': [
    { group: 'C1', models: ['C1 (All)', 'C1 I', 'C1 II', '1.0', '1.2 PureTech'] },
    { group: 'C3', models: ['C3 (All)', 'C3 I', 'C3 II', 'C3 III', '1.0 PureTech', '1.2 PureTech', 'Aircross'] },
    { group: 'C4', models: ['C4 (All)', 'C4 I', 'C4 II', 'C4 III', '1.2 PureTech', '1.5 BlueHDi', 'Cactus', 'e-C4'] },
    { group: 'C5', models: ['C5 (All)', 'C5 I', 'C5 II', 'C5 Aircross', 'C5 X', 'C5 X Hybrid PHEV'] },
    { group: 'Berlingo', models: ['Berlingo (All)', 'Berlingo I', 'Berlingo II', 'Berlingo III', 'Multispace', 'Electric'] },
    { group: 'Dispatch', models: ['Dispatch (All)', 'Dispatch I', 'Dispatch II', 'Dispatch III'] },
  ],
  'Tesla': [
    { group: 'Model 3', models: ['Model 3 (All)', 'Standard Range', 'Long Range', 'Long Range AWD', 'Performance'] },
    { group: 'Model S', models: ['Model S (All)', '60', '75', '85', '90', '100', 'Long Range', 'Plaid', 'Plaid+'] },
    { group: 'Model X', models: ['Model X (All)', '60D', '75D', '90D', '100D', 'Long Range', 'Plaid'] },
    { group: 'Model Y', models: ['Model Y (All)', 'Standard Range', 'Long Range', 'Long Range AWD', 'Performance'] },
    { group: 'Cybertruck', models: ['Cybertruck (All)', 'Single Motor RWD', 'Dual Motor AWD', 'Cyberbeast'] },
    { group: 'Roadster', models: ['Roadster (All)', 'Roadster I', 'Roadster II'] },
  ],
  'Kia': [
    { group: 'Sportage', models: ['Sportage (All)', 'Sportage I', 'Sportage II', 'Sportage III', 'Sportage IV', 'Sportage V', 'Plug-in Hybrid', 'Hybrid'] },
    { group: 'Ceed', models: ["Ceed (All)", "cee'd I", "cee'd II", "cee'd III", 'GT', 'Pro Ceed', 'Sportswagon'] },
    { group: 'EV6', models: ['EV6 (All)', 'EV6 Standard Range', 'EV6 Long Range', 'EV6 GT', 'EV6 GT-Line'] },
    { group: 'EV9', models: ['EV9 (All)', 'EV9 Standard Range', 'EV9 Long Range', 'EV9 GT-Line'] },
    { group: 'Niro', models: ['Niro (All)', 'Hybrid', 'Plug-in Hybrid', 'EV', 'GT-Line'] },
    { group: 'Stinger', models: ['Stinger (All)', '2.0 T-GDi', '2.2 CRDi', '3.3 T-GDi', 'GT', 'GT-Line'] },
    { group: 'Sorento', models: ['Sorento (All)', 'Sorento I', 'Sorento II', 'Sorento III', 'Sorento IV', 'Plug-in Hybrid'] },
    { group: 'Stonic', models: ['Stonic (All)', '1.0 T-GDi', '1.4 MPi', '1.6 CRDi'] },
    { group: 'Soul', models: ['Soul (All)', 'Soul I', 'Soul II', 'Soul III', 'Electric'] },
  ],
  'Hyundai': [
    { group: 'i10', models: ['i10 (All)', 'i10 I', 'i10 II', 'i10 III', '1.0', '1.1', '1.2'] },
    { group: 'i20', models: ['i20 (All)', 'i20 I', 'i20 II', 'i20 III', '1.0 T-GDi', '1.2', '1.4', 'N Line', 'N'] },
    { group: 'i30', models: ['i30 (All)', 'i30 I', 'i30 II', 'i30 III', '1.0 T-GDi', '1.4 T-GDi', '1.5', '2.0 T-GDi', 'N', 'N Line', 'Fastback', 'Wagon'] },
    { group: 'Tucson', models: ['Tucson (All)', 'Tucson I', 'Tucson II', 'Tucson III', 'Tucson IV', '1.6 T-GDi', '2.0 CRDi', 'Plug-in Hybrid', 'Hybrid'] },
    { group: 'Santa Fe', models: ['Santa Fe (All)', 'Santa Fe I', 'Santa Fe II', 'Santa Fe III', 'Santa Fe IV', '2.0 CRDi', '2.2 CRDi', 'Plug-in Hybrid'] },
    { group: 'Ioniq', models: ['Ioniq (All)', 'Ioniq Hybrid', 'Ioniq Plug-in Hybrid', 'Ioniq Electric', 'Ioniq 5', 'Ioniq 6'] },
    { group: 'Kona', models: ['Kona (All)', '1.0 T-GDi', '1.6 T-GDi', '1.6 CRDi', 'Electric', 'N Line', 'N'] },
    { group: 'Bayon', models: ['Bayon (All)', '1.0 T-GDi', '1.2 MPI'] },
  ],
  'Nissan': [
    { group: 'Micra', models: ['Micra (All)', 'Micra III', 'Micra IV', 'Micra V', '0.9 TCe', '1.0 IG-T', '1.2 DIG-S', '1.5 dCi'] },
    { group: 'Juke', models: ['Juke (All)', 'Juke I', 'Juke II', '1.0 DIG-T', '1.2 DIG-T', '1.5 dCi', '1.6 DIG-T', 'Hybrid', 'Nismo'] },
    { group: 'Qashqai', models: ['Qashqai (All)', 'Qashqai I', 'Qashqai II', 'Qashqai III', '1.3 DIG-T', '1.5 dCi', '1.6 dCi', '2.0 dCi', 'e-POWER'] },
    { group: 'X-Trail', models: ['X-Trail (All)', 'X-Trail I', 'X-Trail II', 'X-Trail III', 'X-Trail IV', '1.3 DIG-T', '1.6 dCi', '2.0 dCi', 'e-POWER'] },
    { group: 'Leaf', models: ['Leaf (All)', 'Leaf I', 'Leaf II', '24 kWh', '30 kWh', '40 kWh', '62 kWh'] },
    { group: 'GT-R', models: ['GT-R (All)', 'Premium', 'Black Edition', 'Track Edition', 'Nismo'] },
    { group: 'Navara', models: ['Navara (All)', 'Navara D22', 'Navara D40', 'Navara D23', '2.3 dCi', '2.5 dCi', 'Raptor'] },
  ],
  'Mazda': [
    { group: 'Mazda2', models: ['Mazda2 (All)', 'Mazda2 I', 'Mazda2 II', 'Mazda2 III', 'Mazda2 Hybrid'] },
    { group: 'Mazda3', models: ['Mazda3 (All)', 'Mazda3 I', 'Mazda3 II', 'Mazda3 III', 'Mazda3 IV', '2.0 Skyactiv-X', '2.5 Skyactiv-G'] },
    { group: 'Mazda6', models: ['Mazda6 (All)', 'Mazda6 I', 'Mazda6 II', 'Mazda6 III', '2.0 Skyactiv-G', '2.2 Skyactiv-D', 'Wagon'] },
    { group: 'CX-3', models: ['CX-3 (All)', '1.5 Skyactiv-D', '1.8 Skyactiv-D', '2.0 Skyactiv-G'] },
    { group: 'CX-5', models: ['CX-5 (All)', 'CX-5 I', 'CX-5 II', '2.0 Skyactiv-G', '2.2 Skyactiv-D', '2.5 Turbo'] },
    { group: 'CX-30', models: ['CX-30 (All)', '1.8 Skyactiv-D', '2.0 Skyactiv-G', '2.0 Skyactiv-X', 'e-Skyactiv X'] },
    { group: 'MX-5', models: ['MX-5 (All)', 'NA', 'NB', 'NC', 'ND', '1.5 Skyactiv-G', '2.0 Skyactiv-G', 'RF', 'Miata'] },
    { group: 'CX-60', models: ['CX-60 (All)', 'e-Skyactiv PHEV', 'e-Skyactiv D', 'e-Skyactiv X'] },
  ],
  'Honda': [
    { group: 'Civic', models: ['Civic (All)', 'Civic VI', 'Civic VII', 'Civic VIII', 'Civic IX', 'Civic X', 'Civic XI', 'Type R', 'e:HEV'] },
    { group: 'CR-V', models: ['CR-V (All)', 'CR-V I', 'CR-V II', 'CR-V III', 'CR-V IV', 'CR-V V', 'Hybrid', 'e:PHEV'] },
    { group: 'Jazz', models: ['Jazz (All)', 'Jazz I', 'Jazz II', 'Jazz III', 'Jazz IV', 'e:HEV', 'Crosstar'] },
    { group: 'HR-V', models: ['HR-V (All)', 'HR-V I', 'HR-V II', 'HR-V III', '1.5 e:HEV'] },
    { group: 'e', models: ['Honda e (All)', 'Honda e 100kW', 'Honda e 113kW', 'Advance'] },
    { group: 'Accord', models: ['Accord (All)', 'Accord VI', 'Accord VII', 'Accord VIII', 'Accord IX', '2.0', '2.2 i-DTEC', '2.4', '3.5'] },
    { group: 'NSX', models: ['NSX (All)', 'NSX I', 'NSX II', '3.5 V6 Hybrid'] },
  ],
  'Subaru': [
    { group: 'Impreza', models: ['Impreza (All)', 'Impreza I', 'Impreza II', 'Impreza III', 'Impreza IV', 'WRX', 'WRX STi'] },
    { group: 'Forester', models: ['Forester (All)', 'Forester I', 'Forester II', 'Forester III', 'Forester IV', 'Forester V', 'e-Boxer'] },
    { group: 'Outback', models: ['Outback (All)', 'Outback I', 'Outback II', 'Outback III', 'Outback IV', 'Outback V', 'Outback VI', 'e-Boxer'] },
    { group: 'XV / Crosstrek', models: ['XV (All)', 'XV I', 'XV II', 'e-Boxer', 'Crosstrek'] },
    { group: 'Legacy', models: ['Legacy (All)', 'Legacy I', 'Legacy II', 'Legacy III', 'Legacy IV', 'Legacy V', 'GT', 'Spec B'] },
    { group: 'BRZ', models: ['BRZ (All)', 'BRZ I', 'BRZ II', '2.0', '2.4 Turbo'] },
  ],
  'Seat': [
    { group: 'Ibiza', models: ['Ibiza (All)', 'Ibiza III', 'Ibiza IV', 'Ibiza V', '1.0 TSI', '1.5 TSI', '1.6 TDI', 'FR', 'Cupra'] },
    { group: 'Leon', models: ['Leon (All)', 'Leon I', 'Leon II', 'Leon III', 'Leon IV', '1.0 TSI', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'FR', 'Cupra', 'e-Hybrid', 'Sportstourer'] },
    { group: 'Ateca', models: ['Ateca (All)', '1.0 TSI', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'FR', 'Cupra'] },
    { group: 'Arona', models: ['Arona (All)', '1.0 TSI', '1.5 TSI', '1.6 TDI', 'FR', 'Xcellence'] },
    { group: 'Tarraco', models: ['Tarraco (All)', '1.4 TSI e-Hybrid', '1.5 TSI', '2.0 TDI', '2.0 TSI', 'FR'] },
    { group: 'Alhambra', models: ['Alhambra (All)', 'Alhambra I', 'Alhambra II', '1.4 TSI', '2.0 TDI'] },
  ],
  'Mitsubishi': [
    { group: 'Outlander', models: ['Outlander (All)', 'Outlander I', 'Outlander II', 'Outlander III', '2.0 MIVEC', '2.2 DI-D', '2.4 PHEV', 'Sport'] },
    { group: 'Eclipse Cross', models: ['Eclipse Cross (All)', '1.5 Turbo', '2.4 PHEV'] },
    { group: 'ASX', models: ['ASX (All)', '1.6', '1.8 DI-D', '2.0 MIVEC', '2.2 DI-D'] },
    { group: 'L200', models: ['L200 (All)', 'L200 IV', 'L200 V', '2.4 DI-D', '2.5 DI-D', 'Double Cab', 'Club Cab'] },
    { group: 'Lancer', models: ['Lancer (All)', 'Lancer VIII', 'Lancer IX', 'Lancer X', '1.5', '2.0', 'Evolution', 'EVO X'] },
    { group: 'Pajero', models: ['Pajero (All)', 'Pajero II', 'Pajero III', 'Pajero IV', '3.0 V6', '3.2 DI-D', '3.5 V6', 'Sport'] },
  ],
  'Lexus': [
    { group: 'IS', models: ['IS (All)', 'IS 200', 'IS 220d', 'IS 250', 'IS 300', 'IS 300h', 'IS 350', 'IS 500', 'F', 'C'] },
    { group: 'ES', models: ['ES (All)', 'ES 300h', 'ES 350', 'ES 250'] },
    { group: 'GS', models: ['GS (All)', 'GS 250', 'GS 300', 'GS 300h', 'GS 350', 'GS 430', 'GS 450h', 'F'] },
    { group: 'LS', models: ['LS (All)', 'LS 400', 'LS 430', 'LS 460', 'LS 500', 'LS 500h', 'LS 600h'] },
    { group: 'NX', models: ['NX (All)', 'NX 200t', 'NX 300', 'NX 300h', 'NX 350', 'NX 350h', 'NX 450h+', 'F Sport'] },
    { group: 'RX', models: ['RX (All)', 'RX 300', 'RX 350', 'RX 400h', 'RX 450h', 'RX 450h+', 'RX 500h', 'L'] },
    { group: 'UX', models: ['UX (All)', 'UX 200', 'UX 250h', 'UX 300e', 'F Sport'] },
    { group: 'LX', models: ['LX (All)', 'LX 470', 'LX 570', 'LX 600'] },
    { group: 'LC', models: ['LC (All)', 'LC 500', 'LC 500h', 'LC 500 Convertible'] },
    { group: 'CT', models: ['CT (All)', 'CT 200h', 'F Sport'] },
  ],
  'Dacia': [
    { group: 'Sandero', models: ['Sandero (All)', 'Sandero I', 'Sandero II', 'Sandero III', '1.0 SCe', '1.0 TCe', '1.5 dCi', 'Stepway', 'RS'] },
    { group: 'Duster', models: ['Duster (All)', 'Duster I', 'Duster II', '1.0 TCe', '1.3 TCe', '1.5 dCi', '4x2', '4x4'] },
    { group: 'Logan', models: ['Logan (All)', 'Logan I', 'Logan II', 'Logan III', '1.0 SCe', '1.5 dCi', 'MCV', 'Express'] },
    { group: 'Jogger', models: ['Jogger (All)', '1.0 TCe 100', '1.0 TCe 110', 'Hybrid 140', '7-seat'] },
    { group: 'Spring', models: ['Spring (All)', 'Spring Electric 33kW', 'Spring Electric 45kW', 'Comfort', 'Extreme'] },
  ],
  'Land Rover': [
    { group: 'Range Rover', models: ['Range Rover (All)', 'Range Rover Vogue', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'P400e PHEV', 'D300', 'D350', 'P400', 'P530'] },
    { group: 'Defender', models: ['Defender (All)', 'Defender 90', 'Defender 110', 'Defender 130', '2.0 D', '3.0 D', '3.0 P', 'V8'] },
    { group: 'Discovery', models: ['Discovery (All)', 'Discovery I', 'Discovery II', 'Discovery III', 'Discovery IV', 'Discovery V', 'Sport'] },
    { group: 'Freelander', models: ['Freelander (All)', 'Freelander I', 'Freelander II', '2.0 Si4', '2.2 SD4', '2.2 TD4'] },
  ],
  'Alfa Romeo': [
    { group: 'Giulia', models: ['Giulia (All)', '2.0 Turbo', '2.2 Diesel', '2.9 V6 Biturbo', 'Sprint', 'Veloce', 'Ti', 'Quadrifoglio'] },
    { group: 'Giulietta', models: ['Giulietta (All)', '1.4 Turbo', '1.6 JTDm', '1.75 TBi', '2.0 JTDm', 'Sprint', 'Veloce', 'QV'] },
    { group: 'Stelvio', models: ['Stelvio (All)', '2.0 Turbo', '2.2 Diesel', '2.9 V6 Biturbo', 'Sprint', 'Veloce', 'Ti', 'Quadrifoglio'] },
    { group: 'Tonale', models: ['Tonale (All)', '1.5 Hybrid', '1.6 Diesel', '1.3 PHEV'] },
    { group: '147', models: ['147 (All)', '1.6 TS', '1.9 JTD', '2.0 TS', '3.2 GTA'] },
    { group: '156', models: ['156 (All)', '1.6 TS', '1.8 TS', '1.9 JTD', '2.0 TS', '2.5 V6', 'Crosswagon', 'GTA'] },
  ],
  'Mini': [
    { group: 'Hatch', models: ['Hatch (All)', 'Cooper', 'Cooper S', 'Cooper SE', 'One', 'One D', 'Cooper D', 'John Cooper Works', '3-door', '5-door'] },
    { group: 'Cabrio', models: ['Cabrio (All)', 'Cooper Cabrio', 'Cooper S Cabrio', 'Cooper D Cabrio', 'John Cooper Works Cabrio'] },
    { group: 'Clubman', models: ['Clubman (All)', 'Cooper Clubman', 'Cooper S Clubman', 'Cooper D Clubman', 'John Cooper Works Clubman', 'ALL4'] },
    { group: 'Countryman', models: ['Countryman (All)', 'Cooper Countryman', 'Cooper S Countryman', 'Cooper D Countryman', 'John Cooper Works Countryman', 'ALL4', 'PHEV'] },
    { group: 'Paceman', models: ['Paceman (All)', 'Cooper Paceman', 'Cooper S Paceman', 'ALL4'] },
  ],
  'Fiat': [
    { group: '500', models: ['500 (All)', '500 I', '500 II', '0.9 TwinAir', '1.0 Hybrid', '1.2', '1.3 Multijet', '1.4', 'Abarth 595', 'Abarth 695', '500e'] },
    { group: 'Panda', models: ['Panda (All)', 'Panda I', 'Panda II', 'Panda III', '0.9 TwinAir', '1.0 Hybrid', '1.2', '1.3 Multijet', '4x4', 'Cross'] },
    { group: 'Tipo', models: ['Tipo (All)', '1.0', '1.3 Multijet', '1.4', '1.6 Multijet', '5-door', 'SW', 'Cross'] },
    { group: 'Punto', models: ['Punto (All)', 'Punto I', 'Punto II', 'Punto III', 'Grande Punto', 'Punto Evo', 'Abarth Punto'] },
    { group: 'Doblò', models: ['Doblò (All)', 'Doblò I', 'Doblò II', 'Doblò III', 'Cargo', 'Family', 'Electric'] },
  ],
  'Suzuki': [
    { group: 'Swift', models: ['Swift (All)', 'Swift I', 'Swift II', 'Swift III', 'Swift IV', 'Swift V', '1.0 Boosterjet', '1.2', '1.4 Boosterjet', 'Sport', 'Hybrid'] },
    { group: 'Vitara', models: ['Vitara (All)', 'Vitara I', 'Vitara II', 'Vitara III', '1.0 Boosterjet', '1.4 Boosterjet', '1.6', 'Hybrid', 'AllGrip'] },
    { group: 'Jimny', models: ['Jimny (All)', 'Jimny I', 'Jimny II', 'Jimny III', 'Jimny IV', '1.3', '1.5'] },
    { group: 'SX4 / S-Cross', models: ['SX4 (All)', 'SX4 I', 'SX4 II S-Cross', '1.4 Boosterjet', '1.6', '2.0 DDiS'] },
    { group: 'Ignis', models: ['Ignis (All)', 'Ignis I', 'Ignis II', '1.0 Dualjet Hybrid', '1.2', '1.2 SHVS'] },
  ],
  'Jeep': [
    { group: 'Wrangler', models: ['Wrangler (All)', 'TJ', 'JK', 'JL', '2.0 Turbo', '3.6 V6', '4xe PHEV', 'Sport', 'Sahara', 'Rubicon'] },
    { group: 'Grand Cherokee', models: ['Grand Cherokee (All)', 'ZJ', 'WJ', 'WK', 'WK2', 'WL', '3.0 CRD', '3.6 V6', '5.7 HEMI', '4xe PHEV', 'Laredo', 'Limited', 'Overland', 'Summit'] },
    { group: 'Compass', models: ['Compass (All)', 'Compass I', 'Compass II', '1.3 Turbo', '1.4 MultiAir', '1.6 Multijet', '4xe PHEV'] },
    { group: 'Renegade', models: ['Renegade (All)', '1.0 Turbo', '1.3 Turbo', '1.6 Multijet', '4xe PHEV', 'Sport', 'Limited', 'Trailhawk'] },
    { group: 'Cherokee', models: ['Cherokee (All)', 'XJ', 'KJ', 'KK', 'KL', '2.0 Turbo', '2.4', '3.2 V6', 'Trailhawk'] },
  ],
  'Chevrolet': [
    { group: 'Camaro', models: ['Camaro (All)', '2.0 Turbo', '3.6 V6', '6.2 V8', 'LS', 'LT', 'SS', 'ZL1'] },
    { group: 'Corvette', models: ['Corvette (All)', 'C5', 'C6', 'C7', 'C8', 'Stingray', 'Z06', 'ZR1', 'Grand Sport'] },
    { group: 'Cruze', models: ['Cruze (All)', 'Cruze I', 'Cruze II', '1.4 Turbo', '1.6', '1.8', '2.0 CDTi'] },
    { group: 'Captiva', models: ['Captiva (All)', 'Captiva I', 'Captiva II', '2.0 CDTi', '2.4', '3.2 V6'] },
    { group: 'Trax', models: ['Trax (All)', '1.4 Turbo', '1.6', '1.7 CDTi'] },
    { group: 'Spark', models: ['Spark (All)', '1.0', '1.2', 'EV'] },
  ],
};
